lambda enhancements (#14)
- lambda_deploy() will deploy via S3 if DEPLOY_LAMBDA_S3_BUCKET is set
- lambda_deploy() will throw an error if DEPLOY_LAMBDA_S3_BUCKET is not set and the zip is less than 50MB
- some other minor lambda-related code cleanup

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -44,6 +44,15 @@ JQ="jq --raw-output --exit-status"
 
 DEPLOY_CURRENT_TIME="$(date +%Y%m%d)"
 
+##
+## lambda defaults
+##
+
+DEPLOY_LAMBDA_FUNCTION_RUNTIME="${DEPLOY_LAMBDA_FUNCTION_RUNTIME:-nodejs6.10}"
+DEPLOY_LAMBDA_FUNCTION_HANDLER="${DEPLOY_LAMBDA_FUNCTION_HANDLER:-index.handler}"
+DEPLOY_LAMBDA_FUNCTION_TIMEOUT="${DEPLOY_LAMBDA_FUNCTION_TIMEOUT:-3}"
+DEPLOY_LAMBDA_FUNCTION_MEMORY_SIZE="${DEPLOY_LAMBDA_FUNCTION_MEMORY_SIZE:-128}"
+
 
 ##
 ## private functions
@@ -598,7 +607,7 @@ function _ecs_update_service() {
 
 
 ##
-## lamdba
+## lambda
 ##
 
 function _lambda_init_zip_vars () {
@@ -707,6 +716,11 @@ function lambda_update_from_s3 () {
         exit 1
     fi
 
+    if [[ -z "${DEPLOY_LAMBDA_FUNCTION_ROLE}" ]] ; then
+        echo "Error: DEPLOY_LAMBDA_FUNCTION_ROLE is required"
+        exit 1
+    fi
+
     if [[ -z "${DEPLOY_LAMBDA_S3_BUCKET}" ]] ; then
         echo "Error: DEPLOY_LAMBDA_S3_BUCKET is required"
         exit 1
@@ -715,13 +729,45 @@ function lambda_update_from_s3 () {
     # setup aws
     aws_configure
 
+
+    lambda_env_template="${DEPLOY_LAMBDA_FUNCTION_ENV_TEMPLATE:-environment.txt}"
+
+    if [[ -f ${lambda_env_template} ]] ; then
+      lambda_env=$( \
+          ${DEPLOY_ENVSUBST_COMMAND:-envsubst} < "${lambda_env_template}"
+      )
+    fi
+
+    echo "Info: Attemping to update existing lambda function"
+
+    lambda_role="arn:aws:iam::${DEPLOY_AWS_ACCOUNT}:role/${DEPLOY_LAMBDA_FUNCTION_ROLE}"
+
+    lambda_function_arn=$( \
+        aws lambda update-function-configuration \
+            --profile       "${DEPLOY_AWS_PROFILE}" \
+            --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
+            --description   "${DEPLOY_LAMBDA_FUNCTION_DESCRIPTION}" \
+            --handler       "${DEPLOY_LAMBDA_FUNCTION_HANDLER}" \
+            --memory-size   "${DEPLOY_LAMBDA_FUNCTION_MEMORY_SIZE}" \
+            --runtime       "${DEPLOY_LAMBDA_FUNCTION_RUNTIME}" \
+            --timeout       "${DEPLOY_LAMBDA_FUNCTION_TIMEOUT}" \
+            --role          "${lambda_role}" \
+            ${lambda_env:+ --environment "${lambda_env}"} \
+        | $JQ ".FunctionArn"
+    )
+
+    if [[ -z "${lambda_function_arn}" ]] ; then
+        echo "Error: Failed to update lambda function configuration"
+        exit 1
+    fi
+
     # update lambda function
     lambda_function_sha256=$( \
         aws lambda update-function-code \
-            --profile "${DEPLOY_AWS_PROFILE}" \
-            --function-name "${DEPLOY_LAMBDA_TARGET_FUNCTION_NAME:-$DEPLOY_LAMBDA_FUNCTION_NAME}" \
-            --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
-            --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip" \
+            --profile       "${DEPLOY_AWS_PROFILE}" \
+            --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
+            --s3-bucket     "${DEPLOY_LAMBDA_S3_BUCKET}" \
+            --s3-key        "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip" \
         | $JQ ".CodeSha256"
     )
 
@@ -734,9 +780,9 @@ function lambda_update_from_s3 () {
 
         lambda_function_version=$( \
             aws lambda publish-version \
-                --profile "${DEPLOY_AWS_PROFILE}" \
-                --function-name "${DEPLOY_LAMBDA_TARGET_FUNCTION_NAME:-$DEPLOY_LAMBDA_FUNCTION_NAME}" \
-                --description "${DEPLOY_LAMBDA_ZIP_VERSION} created by deployables" \
+                --profile       "${DEPLOY_AWS_PROFILE}" \
+                --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
+                --description   "${DEPLOY_LAMBDA_ZIP_VERSION} created by deployables" \
                 --code-sha-256 "${lambda_function_sha256}" \
             | $JQ ".Version"
         )
@@ -778,11 +824,31 @@ function lambda_deploy () {
         lambda_package_zip
     fi
 
-    lamdba_runtime="${DEPLOY_LAMBDA_FUNCTION_RUNTIME:-nodejs6.10}"
-    lamdba_handler="${DEPLOY_LAMBDA_FUNCTION_HANDLER:-index.handler}"
+    # check zip for file size limits
+    local bytes=$( stat -c%s "$DEPLOY_LAMBDA_ZIP_FULLPATH" )
+    DEPLOY_LAMBDA_ZIP_FILESIZE=$(( bytes / 1024 / 1024 ))
+
+    if [[ ! -z "${DEPLOY_LAMBDA_S3_BUCKET}" ]] ; then
+      echo "Info: Deploying lambda via S3; DEPLOY_LAMBDA_S3_BUCKET: ${DEPLOY_LAMBDA_S3_BUCKET}"
+
+      lambda_code_parameters=$( echo \
+         --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
+         --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip"
+      )
+
+    elif [[ "${DEPLOY_LAMBDA_ZIP_FILESIZE}" -lt "50" ]] ; then
+      echo "Info: Deploying code directly; Lambda zip file size is less than 50MB"
+
+      lambda_code_parameters=$( echo \
+          --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}"
+      )
+
+    else
+      echo "Error: Unable to deploy lambda zip larger than 50MB; DEPLOY_LAMBDA_ZIP_FILESIZE: ${DEPLOY_LAMBDA_ZIP_FILESIZE}"
+      exit 1
+    fi
+
     lambda_role="arn:aws:iam::${DEPLOY_AWS_ACCOUNT}:role/${DEPLOY_LAMBDA_FUNCTION_ROLE}"
-    lambda_timeout="${DEPLOY_LAMBDA_FUNCTION_TIMEOUT:-3}"
-    lambda_memory_size="${DEPLOY_LAMBDA_FUNCTION_MEMORY_SIZE:-128}"
 
     lambda_env_template="${DEPLOY_LAMBDA_FUNCTION_ENV_TEMPLATE:-environment.txt}"
 
@@ -800,19 +866,21 @@ function lambda_deploy () {
             --profile "${DEPLOY_AWS_PROFILE}" \
             --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
             --description "${DEPLOY_LAMBDA_FUNCTION_DESCRIPTION}" \
-            --timeout "${lambda_timeout}" \
-            --memory-size "${lambda_memory_size}" \
+            --timeout "${DEPLOY_LAMBDA_FUNCTION_TIMEOUT}" \
+            --memory-size "${DEPLOY_LAMBDA_FUNCTION_MEMORY_SIZE}" \
             --role "${lambda_role}" \
-            --handler "${lamdba_handler}" \
-            --runtime "${lamdba_runtime}" \
+            --handler "${DEPLOY_LAMBDA_FUNCTION_HANDLER}" \
+            --runtime "${DEPLOY_LAMBDA_FUNCTION_RUNTIME}" \
             ${lambda_env:+ --environment "${lambda_env}"} \
-            --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}" \
+            ${DEPLOY_LAMBDA_PUBLISH_NEW_VERSION:+ --publish} \
+            ${lambda_code_parameters} \
         | $JQ ".FunctionArn"
     )
 
     # try to update the lamda function if creation failed
     if [[ -z "$lambda_function_arn" ]] ; then
 
+        echo "Info: Creating a new lambda function failed"
         echo "Info: Attemping to update existing lambda function"
 
         lambda_function_arn=$( \
@@ -820,12 +888,12 @@ function lambda_deploy () {
                 --profile "${DEPLOY_AWS_PROFILE}" \
                 --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
                 --description "${DEPLOY_LAMBDA_FUNCTION_DESCRIPTION}" \
-                --timeout "${lambda_timeout}" \
-                --memory-size "${lambda_memory_size}" \
+                --timeout "${DEPLOY_LAMBDA_FUNCTION_TIMEOUT}" \
+                --memory-size "${DEPLOY_LAMBDA_FUNCTION_MEMORY_SIZE}" \
                 --role "${lambda_role}" \
-                --handler "${lamdba_handler}" \
+                --handler "${DEPLOY_LAMBDA_FUNCTION_HANDLER}" \
+                --runtime "${DEPLOY_LAMBDA_FUNCTION_RUNTIME}" \
                 ${lambda_env:+ --environment "${lambda_env}"} \
-                --runtime "${lamdba_runtime}" \
             | $JQ ".FunctionArn"
         )
 
@@ -834,33 +902,14 @@ function lambda_deploy () {
           aws lambda update-function-code \
               --profile "${DEPLOY_AWS_PROFILE}" \
               --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
-              --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}" \
+              ${DEPLOY_LAMBDA_PUBLISH_NEW_VERSION:+ --publish} \
+              ${lambda_code_parameters} \
           | $JQ ".CodeSha256"
         )
 
         if [[ -z "${lambda_function_sha256}" ]] ; then
             echo "Error: Failed to update lambda function"
             exit 1
-        fi
-
-        if [[ ! -z "${DEPLOY_LAMBDA_PUBLISH_NEW_VERSION}" ]] ; then
-
-            echo "Info: Attemping to publish new version of the lambda function"
-
-            lambda_function_version=$( \
-                aws lambda publish-version \
-                    --profile "${DEPLOY_AWS_PROFILE}" \
-                    --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
-                    --description "New version published by deployables" \
-                    --code-sha-256 "${lambda_function_sha256}" \
-                | $JQ ".Version"
-            )
-
-            if [[ -z "${lambda_function_version}" ]] ; then
-                echo "Error: Failed to publish lambda version"
-                exit 1
-            fi
-
         fi
 
     fi
