move lambda zip to it's own function

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -514,6 +514,22 @@ function ecs_deploy () {
 
 }
 
+function package_lambda () {
+
+    #
+    # zip into deploy package
+    #
+    pushd "${DEPLOY_LAMBDA_FUNCTION_ZIP_DIR:-.}"
+    zip -q -r ../$DEPLOY_LAMBDA_FUNCTION_NAME . -x "*.git*"
+    popd
+
+    if [[ "$?" != "0" ]] ; then
+        echo "Error: Failed to create lambda zip archive"
+        exit 1
+    fi
+
+}
+
 function deploy_lambda () {
 
     # check environment variables
@@ -535,17 +551,8 @@ function deploy_lambda () {
     # setup aws
     aws_configure
 
-    #
-    # zip into deploy package
-    #
-    pushd "${DEPLOY_LAMBDA_FUNCTION_ZIP_DIR:-.}"
-    zip -q -r ../$DEPLOY_LAMBDA_FUNCTION_NAME . -x "*.git*"
-    popd
-
-    if [[ "$?" != "0" ]] ; then
-        echo "Error: Failed to create lambda zip archive"
-        exit 1
-    fi
+    # zip the
+    package_lambda
 
     lamdba_runtime="${DEPLOY_LAMBDA_FUNCTION_RUNTIME:-nodejs4.3}"
     lamdba_handler="${DEPLOY_LAMBDA_FUNCTION_HANDLER:-index.handler}"
