initial pass at publish lambda version

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -631,28 +631,38 @@ function lambda_update_from_s3 () {
     aws_configure
 
     # update lambda function
-    lambda_function_arn=$( \
+    lambda_function_revid=$( \
         aws lambda update-function-code \
             --profile "${DEPLOY_AWS_PROFILE}" \
             --function-name "${DEPLOY_LAMBDA_TARGET_FUNCTION_NAME:-DEPLOY_LAMBDA_FUNCTION_NAME}" \
             --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
             --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip" \
-        | $JQ ".FunctionArn"
+        | $JQ ".RevisionId"
     )
 
-    if [[ -z "$lambda_function_arn" ]] ; then
+    if [[ -z "${lambda_function_revid}" ]] ; then
       echo "Error: Failed to deploy lambda function"
       exit 1
     fi
 
-    if [[
-publish-version
---function-name <value>
-[--code-sha-256 <value>]
-[--description <value>]
-[--revision-id <value>]
-[--cli-input-json <value>]
-[--generate-cli-skeleton <value>]
+
+    if [[ ! -z "${DEPLOY_LAMBDA_ZIP_VERSION}" ]] ; then
+
+      lambda_function_version=$( \
+        aws lambda publish-version \
+            --profile "${DEPLOY_AWS_PROFILE}" \
+            --function-name "${DEPLOY_LAMBDA_TARGET_FUNCTION_NAME:-DEPLOY_LAMBDA_FUNCTION_NAME}" \
+            --description "${DEPLOY_LAMBDA_ZIP_VERSION} created by deployables"
+            --revision-id "${lambda_function_revid}"
+        | $JQ ".Version"
+      )
+
+      if [[ -z "${lambda_function_version}" ]] ; then
+        echo "Error: Failed to publish lambda version"
+        exit 1
+      fi
+
+    fi
 
 }
 
