minor refactoring and function name cleanup

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -535,18 +535,20 @@ function ecs_deploy () {
 
 }
 
-function package_lambda () {
+function lambda_package_zip () {
 
     DEPLOY_LAMBDA_SOURCE_DIR="${DEPLOY_LAMBDA_SOURCE_DIR:-.}"
 
-    DEPLOY_LAMBDA_ZIP_DIR="${DEPLOY_LAMBDA_ZIP_DIR:-/tmp/deploy_artifacts}"
-    mkdir -p ${DEPLOY_LAMBDA_ZIP_DIR}
+    if [ -z "${DEPLOY_LAMBDA_ZIP_FULLPATH}" ] ; then
+        DEPLOY_LAMBDA_ZIP_DIR="${DEPLOY_LAMBDA_ZIP_DIR:-/tmp/deploy_artifacts}"
+        mkdir -p ${DEPLOY_LAMBDA_ZIP_DIR}
 
-    if [ -z "${DEPLOY_LAMBDA_ZIP_FILENAME}" ] ; then
-        DEPLOY_LAMBDA_ZIP_FILENAME="${DEPLOY_LAMBDA_FUNCTION_NAME}.zip"
+        if [ -z "${DEPLOY_LAMBDA_ZIP_FILENAME}" ] ; then
+            DEPLOY_LAMBDA_ZIP_FILENAME="${DEPLOY_LAMBDA_FUNCTION_NAME}.zip"
+        fi
+
+        DEPLOY_LAMBDA_ZIP_FULLPATH="${DEPLOY_LAMBDA_ZIP_DIR}/${DEPLOY_LAMBDA_ZIP_FILENAME}"
     fi
-
-    DEPLOY_LAMBDA_ZIP_FULLPATH="${DEPLOY_LAMBDA_ZIP_DIR}/${DEPLOY_LAMBDA_ZIP_FILENAME}"
 
     if [ -z "${DEPLOY_DEBUG}" ] ; then
         DEPLOY_LAMBDA_ZIP_QUIET="-q"
@@ -566,36 +568,86 @@ function package_lambda () {
 
 }
 
-function copy_lambda_to_s3 () {
+function lambda_copy_zip_to_s3 () {
 
     aws_configure
 
+    # copy to version-specific or commit-hash key
+    if [ ! -z "${DEPLOY_LAMBDA_ZIP_VERSION}" ] ; then
+        aws --profile "${DEPLOY_AWS_PROFILE}" \
+            s3 cp \
+            ${DEPLOY_LAMBDA_ZIP_FULLPATH} \
+            s3://${DEPLOY_LAMBDA_S3_BUCKET}/${DEPLOY_LAMBDA_FUNCTION_NAME}/archive/${DEPLOY_LAMBDA_FUNCTION_NAME}-${DEPLOY_LAMBDA_ZIP_VERSION}.zip
+
+        if [[ "$?" != "0" ]] ; then
+            echo "Error: Failed to copy lambda zip to S3 (${DEPLOY_LAMBDA_ZIP_VERSION})"
+            exit 1
+        fi
+
+    elif [ ! -z "${DEPLOY_SHA1}" ] ; then
+        aws --profile "${DEPLOY_AWS_PROFILE}" \
+            s3 cp \
+            ${DEPLOY_LAMBDA_ZIP_FULLPATH} \
+            s3://${DEPLOY_LAMBDA_S3_BUCKET}/${DEPLOY_LAMBDA_FUNCTION_NAME}/archive/${DEPLOY_LAMBDA_FUNCTION_NAME}-${DEPLOY_SHA1}.zip
+
+        if [[ "$?" != "0" ]] ; then
+            echo "Error: Failed to copy lambda zip to S3 (${DEPLOY_SHA1})"
+            exit 1
+        fi
+    fi
+
+    # copy to latest key
     aws --profile "${DEPLOY_AWS_PROFILE}" \
         s3 cp \
         ${DEPLOY_LAMBDA_ZIP_FULLPATH} \
-        s3://${DEPLOY_LAMBDA_S3_BUCKET}/${DEPLOY_LAMBDA_FUNCTION_NAME}/archive/${DEPLOY_LAMBDA_FUNCTION_NAME}-${DEPLOY_SHA1}.zip
+        s3://${DEPLOY_LAMBDA_S3_BUCKET}/${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip
 
     if [[ "$?" != "0" ]] ; then
-        echo "Error: Failed to copy lambda zip to S3 (${DEPLOY_SHA1})"
+        echo "Error: Failed to copy lambda zip to S3 (latest)"
         exit 1
-    fi
-
-    if [ ! -z "${DEPLOY_LAMBDA_ZIP_VERSION}" ] ; then
-      aws --profile "${DEPLOY_AWS_PROFILE}" \
-          s3 cp \
-          ${DEPLOY_LAMBDA_ZIP_FULLPATH} \
-          s3://${DEPLOY_LAMBDA_S3_BUCKET}/${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}-${DEPLOY_LAMBDA_ZIP_VERSION}.zip
-
-      if [[ "$?" != "0" ]] ; then
-          echo "Error: Failed to copy lambda zip to S3 (${DEPLOY_LAMBDA_ZIP_VERSION})"
-          exit 1
-      fi
-
     fi
 
 }
 
-function deploy_lambda () {
+function lambda_update_from_s3 () {
+
+    # check environment variables
+    if [ -z "${DEPLOY_AWS_ACCOUNT}" ] ; then
+        echo "Error: DEPLOY_AWS_ACCOUNT is required"
+        exit 1
+    fi
+
+    if [ -z "${DEPLOY_LAMBDA_FUNCTION_NAME}" ] ; then
+        echo "Error: DEPLOY_LAMBDA_FUNCTION_NAME is required"
+        exit 1
+    fi
+
+    if [ -z "${DEPLOY_LAMBDA_S3_BUCKET}" ] ; then
+        echo "Error: DEPLOY_LAMBDA_S3_BUCKET is required"
+        exit 1
+    fi
+
+    # setup aws
+    aws_configure
+
+    # update lambda function
+    lambda_function_arn=$( \
+        aws lambda update-function-code \
+            --profile "${DEPLOY_AWS_PROFILE}" \
+            --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
+            --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
+            --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip" \
+        | $JQ ".FunctionArn"
+    )
+
+    if [[ -z "$lambda_function_arn" ]] ; then
+      echo "Error: Failed to deploy lambda function"
+      exit 1
+    fi
+
+}
+
+function lambda_deploy () {
 
     # check environment variables
     if [ -z "${DEPLOY_AWS_ACCOUNT}" ] ; then
@@ -617,7 +669,7 @@ function deploy_lambda () {
     aws_configure
 
     # zip the
-    package_lambda
+    lambda_package_zip
 
     lamdba_runtime="${DEPLOY_LAMBDA_FUNCTION_RUNTIME:-nodejs4.3}"
     lamdba_handler="${DEPLOY_LAMBDA_FUNCTION_HANDLER:-index.handler}"
@@ -679,7 +731,7 @@ function deploy_lambda () {
         $lambda_function_arn
 }
 
-function deploy_lambda_event {
+function lambda_deploy_event () {
     if [[ -z "${DEPLOY_LAMBDA_EVENT_RULE}" ]] ; then
         echo "Info: No DEPLOY_LAMBDA_EVENT_RULE, not deploying event."
         return
@@ -751,9 +803,24 @@ function deploy_lambda_event {
     fi
 }
 
+function deploy_lambda () {
+    echo "Deprecated: Please use lambda_deploy()"
+    deploy_lambda
+}
+
+function deploy_lambda_event () {
+    echo "Deprecated: Please use lambda_deploy_event()"
+    lambda_deploy_event
+}
+
 ##
 ## MAIN
 ##
+
+# circle v2 hack:  source env file
+if [ ! -z "${DEPLOY_ENV_FILE}" ] ; then
+  source $
+fi
 
 # call arguments verbatim:
 $@
