update checks on the new param

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -618,17 +618,12 @@ function deploy_lambda_event {
         return
     fi
 
-    if [[ -z "${DEPLOY_LAMBDA_EVENT_BASENAME}" ]] ; then
-        echo "Error: 'DEPLOY_LAMBDA_EVENT_BASENAME' is required for deploy_lambda_event."
-        exit 1
-    fi
-
     aws_configure
 
     lambda_event_basename="${1:-$DEPLOY_LAMBDA_EVENT_BASENAME}"
     lambda_function_arn="${2:-$DEPLOY_LAMBDA_FUNCTION_ARN}"
-    event_rule_name="${DEPLOY_LAMBDA_EVENT_BASENAME}_rule"
-    permission_statement_id="${DEPLOY_LAMBDA_EVENT_BASENAME}_permission"
+    event_rule_name="${lambda_event_basename}_rule"
+    permission_statement_id="${lambda_event_basename}_permission"
 
     # this json is a sub-json to something else, so we need to escape the quotes because
     # the aws cli is stupid
@@ -638,6 +633,12 @@ function deploy_lambda_event {
         echo "Error: DEPLOY_LAMBDA_FUNCTION_ARN or passing a 'lambda_function_arn' is required for deploy_lambda_event."
         exit 1
     fi
+
+    if [[ -z "${lambda_event_basename}" ]] ; then
+        echo "Error: DEPLOY_LAMBDA_EVENT_BASENAME or passing the basename is required for deploy_lambda_event."
+        exit 1
+    fi
+
 
     # create or update a cloudwatch event rule
     event_rule_arn=$( \
@@ -668,7 +669,7 @@ function deploy_lambda_event {
         aws events put-targets \
             --profile "${DEPLOY_AWS_PROFILE}" \
             --rule "${event_rule_name}" \
-            --targets "[{ \"Id\" : \"${DEPLOY_LAMBDA_EVENT_BASENAME}_target\", \"Arn\": \"${lambda_function_arn}\" ${DEPLOY_LAMBDA_TARGET_INPUT_JSON:+,\"Input\": \"${input_json_escaped}\"}}]" \
+            --targets "[{ \"Id\" : \"${lambda_event_basename}_target\", \"Arn\": \"${lambda_function_arn}\" ${DEPLOY_LAMBDA_TARGET_INPUT_JSON:+,\"Input\": \"${input_json_escaped}\"}}]" \
             | $JQ ".FailedEntryCount"
     )
 
