test adaptive lambda code deploys

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -653,10 +653,6 @@ function lambda_package_zip () {
         exit 1
     fi
 
-    local bytes=$( stat -c%s "$DEPLOY_LAMBDA_ZIP_FULLPATH" )
-    DEPLOY_LAMBDA_ZIP_FILESIZE=$(( bytes / 1024 / 1024 ))
-    echo "DEPLOY_LAMBDA_ZIP_FILESIZE: ${DEPLOY_LAMBDA_ZIP_FILESIZE}"
-
 }
 
 function lambda_copy_zip_to_s3 () {
@@ -828,6 +824,31 @@ function lambda_deploy () {
         lambda_package_zip
     fi
 
+    # check zip for file size limits
+    local bytes=$( stat -c%s "$DEPLOY_LAMBDA_ZIP_FULLPATH" )
+    DEPLOY_LAMBDA_ZIP_FILESIZE=$(( bytes / 1024 / 1024 ))
+
+    if [[ "${DEPLOY_LAMBDA_ZIP_FILESIZE}" -lt "50" ]] ; then
+      echo "Info: Lambda zip file size is less than 50MB; Deploying code directly"
+      lambda_code_parameters=$( echo -- \
+          --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}"
+      )
+    else
+      if [[ ! -z "${DEPLOY_LAMBDA_S3_BUCKET}" ]] ; then
+        echo "Info: Lambda zip file size is greater than 50MB; attempting to deploy via S3"
+        lambda_code_parameters = $( echo -- \
+           --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
+           --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip"
+        )
+      else
+        echo "Error: Unable to deploy lambda zip larger than 50MB without DEPLOY_LAMBDA_S3_BUCKET set"
+        exit 1
+
+      fi
+    fi
+
+    echo "DEPLOY_LAMBDA_ZIP_FILESIZE: ${DEPLOY_LAMBDA_ZIP_FILESIZE}"
+
     lambda_role="arn:aws:iam::${DEPLOY_AWS_ACCOUNT}:role/${DEPLOY_LAMBDA_FUNCTION_ROLE}"
 
     lambda_env_template="${DEPLOY_LAMBDA_FUNCTION_ENV_TEMPLATE:-environment.txt}"
@@ -853,7 +874,7 @@ function lambda_deploy () {
             --runtime "${DEPLOY_LAMBDA_FUNCTION_RUNTIME}" \
             ${lambda_env:+ --environment "${lambda_env}"} \
             ${DEPLOY_LAMBDA_PUBLISH_NEW_VERSION:+ --publish} \
-            --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}" \
+            ${lambda_code_parameters}
         | $JQ ".FunctionArn"
     )
 
@@ -882,7 +903,7 @@ function lambda_deploy () {
               --profile "${DEPLOY_AWS_PROFILE}" \
               --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
               ${DEPLOY_LAMBDA_PUBLISH_NEW_VERSION:+ --publish} \
-              --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}" \
+              ${lambda_code_parameters} \
           | $JQ ".CodeSha256"
         )
 
