always deploy via S3 if DEPLOY_LAMBDA_S3_BUCKET is set

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -828,24 +828,24 @@ function lambda_deploy () {
     local bytes=$( stat -c%s "$DEPLOY_LAMBDA_ZIP_FULLPATH" )
     DEPLOY_LAMBDA_ZIP_FILESIZE=$(( bytes / 1024 / 1024 ))
 
-    if [[ "${DEPLOY_LAMBDA_ZIP_FILESIZE}" -lt "50" ]] ; then
+    if [[ ! -z "${DEPLOY_LAMBDA_S3_BUCKET}" ]] ; then
+      echo "Info: Deploy lambda via S3; DEPLOY_LAMBDA_S3_BUCKET: ${DEPLOY_LAMBDA_S3_BUCKET}"
+
+      lambda_code_parameters=$( echo \
+         --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
+         --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip"
+      )
+
+    elif [[ "${DEPLOY_LAMBDA_ZIP_FILESIZE}" -lt "50" ]] ; then
       echo "Info: Lambda zip file size is less than 50MB; Deploying code directly"
+
       lambda_code_parameters=$( echo \
           --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}"
       )
-    else
-      if [[ ! -z "${DEPLOY_LAMBDA_S3_BUCKET}" ]] ; then
-        echo "Info: Lambda zip file size is greater than 50MB; attempting to deploy via S3"
-        echo "Info: DEPLOY_LAMBDA_ZIP_FILESIZE: ${DEPLOY_LAMBDA_ZIP_FILESIZE}"
-        lambda_code_parameters=$( echo \
-           --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
-           --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip"
-        )
-      else
-        echo "Error: Unable to deploy lambda zip larger than 50MB without DEPLOY_LAMBDA_S3_BUCKET set"
-        exit 1
 
-      fi
+    else
+      echo "Error: Unable to deploy lambda zip larger than 50MB; DEPLOY_LAMBDA_ZIP_FILESIZE: ${DEPLOY_LAMBDA_ZIP_FILESIZE}"
+      exit 1
     fi
 
     lambda_role="arn:aws:iam::${DEPLOY_AWS_ACCOUNT}:role/${DEPLOY_LAMBDA_FUNCTION_ROLE}"
