separated aws events calls from aws lambda calls

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -510,23 +510,18 @@ function deploy_lambda () {
 
     # check environment variables
     if [ -z "${DEPLOY_AWS_ACCOUNT}" ] ; then
-    echo "Error: DEPLOY_AWS_ACCOUNT is required"
-    exit 1
+        echo "Error: DEPLOY_AWS_ACCOUNT is required"
+        exit 1
     fi
 
     if [ -z "${DEPLOY_LAMBDA_FUNCTION_NAME}" ] ; then
-    echo "Error: DEPLOY_LAMBDA_FUNCTION_NAME is required"
-    exit 1
+        echo "Error: DEPLOY_LAMBDA_FUNCTION_NAME is required"
+        exit 1
     fi
 
     if [ -z "${DEPLOY_LAMBDA_FUNCTION_ROLE}" ] ; then
-    echo "Error: DEPLOY_LAMBDA_FUNCTION_ROLE is required"
-    exit 1
-    fi
-
-    if [ -z "${DEPLOY_LAMBDA_EVENT_RULE}" ] ; then
-    echo "Error: DEPLOY_LAMBDA_EVENT_RULE is required"
-    exit 1
+        echo "Error: DEPLOY_LAMBDA_FUNCTION_ROLE is required"
+        exit 1
     fi
 
     # setup aws
@@ -535,19 +530,9 @@ function deploy_lambda () {
     # zip into deploy package
     zip -q -r ../$DEPLOY_LAMBDA_FUNCTION_NAME .
 
-    lambda_rule_name="${DEPLOY_LAMBDA_FUNCTION_NAME}_rule"
     lamdba_runtime="${DEPLOY_LAMBDA_FUNCTION_RUNTIME:-nodejs4.3}"
     lamdba_handler="${DEPLOY_LAMBDA_FUNCTION_HANDLER:-index.handler}"
     lambda_role="arn:aws:iam::${DEPLOY_AWS_ACCOUNT}:role/${DEPLOY_LAMBDA_FUNCTION_ROLE}"
-
-    # create or update a cloudwatch event rule
-    lambda_rule_arn=$( \
-        aws events put-rule \
-            --profile "${DEPLOY_AWS_PROFILE}" \
-            --name "${lambda_rule_name}" \
-            --schedule-expression "${DEPLOY_LAMBDA_EVENT_RULE}" \
-            | $JQ ".RuleArn"
-    )
 
     lambda_env_template="${DEPLOY_LAMBDA_FUNCTION_ENV_TEMPLATE:-environment.txt}"
 
@@ -592,20 +577,73 @@ function deploy_lambda () {
 
     fi
 
+    if [[ -z "$lambda_function_arn" ]] ; then
+        echo "Error: Failed to deploy lambda function"
+        exit 1
+    fi
+
+    if [[ ! -z "${DEPLOY_LAMBDA_EVENT_RULE}" ]] ; then
+        deploy_lambda_event_rule \
+            $DEPLOY_LAMBDA_FUNCTION_NAME \
+            $lambda_function_arn
+    fi
+
+}
+
+function deploy_lambda_event_rule {
+
+    lambda_function_name="$1"
+    lambda_function_arn="$2"
+
+    if [ -z "${lambda_function_name}" ] ; then
+        echo "Error: Passing a 'lambda_function_name' is required"
+        exit 1
+    fi
+
+    if [ -z "${lambda_function_arn}" ] ; then
+        echo "Error: Passing a 'lambda_function_arn' is required"
+        exit 1
+    fi
+
+    if [[ -z "${DEPLOY_LAMBDA_EVENT_RULE}" ]] ; then
+        echo "Error: DEPLOY_LAMBDA_EVENT_RULE is required"
+        exit 1
+    fi
+
+    event_rule_name="${lambda_function_name}_rule"
+
+    # create or update a cloudwatch event rule
+    event_rule_arn=$( \
+        aws events put-rule \
+            --profile "${DEPLOY_AWS_PROFILE}" \
+            --name "${event_rule_name}" \
+            --schedule-expression "${DEPLOY_LAMBDA_EVENT_RULE}" \
+            | $JQ ".RuleArn"
+    )
+
     # give permissions
     aws lambda add-permission \
         --profile "${DEPLOY_AWS_PROFILE}" \
-        --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
+        --function-name "${lambda_function_arn}" \
         --statement-id "1" \
         --action "lambda:InvokeFunction" \
         --principal "events.amazonaws.com" \
-        --source-arn "${lambda_rule_arn}"
+        --source-arn "${event_rule_arn}"
 
     # add the lambda function to the created rule (i.e.,target the lambda function with the newly created rule)
-    aws events put-targets \
-        --profile "${DEPLOY_AWS_PROFILE}" \
-        --rule "${lambda_rule_name}" \
-        --targets "[{ \"Id\" : \"1\", \"Arn\": \"${lambda_function_arn}\"}]"
+    failed_entry_count=$( \
+        aws events put-targets \
+            --profile "${DEPLOY_AWS_PROFILE}" \
+            --rule "${event_rule_name}" \
+            --targets "[{ \"Id\" : \"1\", \"Arn\": \"${lambda_function_arn}\"}]" \
+            | $JQ ".FailedEntryCount"
+    )
+
+    if [[ "${failed_entry_count}" != "0" ]] ; then
+        echo "Error: Failed associating event rule to lambda function"
+        exit 1
+    fi
+
 }
 
 ##
