catch lambda update error

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -753,10 +753,17 @@ function lambda_deploy () {
         )
 
         # update lambda function
-        aws lambda update-function-code \
+        lambda_update_function_rval=$( \
+          aws lambda update-function-code \
             --profile "${DEPLOY_AWS_PROFILE}" \
             --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
             --zip-file "fileb://${DEPLOY_LAMBDA_ZIP_FULLPATH}"
+        )
+
+        if [[ $lambda_update_function_rval != 0 ]] ; then
+            echo "Error: Failed to update lambda function"
+            exit 1
+        fi
 
     fi
 
