rename and rearrange some functions

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -122,6 +122,68 @@ function aws_run () {
   aws --profile=${DEPLOY_AWS_PROFILE} ${@:1}
 }
 
+##
+## docker
+##
+
+function docker_build {
+
+    echo
+    echo Building docker image
+    echo DEPLOY_DOCKERFILE: ${DEPLOY_DOCKERFILE}
+    echo DEPLOY_DOCKER_LOCAL_TAG: ${DEPLOY_DOCKER_LOCAL_TAG}
+    echo
+
+    if [[ -z "${DEPLOY_DOCKERFILE}" ]] ; then
+        echo "Error: DEPLOY_DOCKERFILE is required"
+        return 1
+    fi
+
+    if [[ -z "${DEPLOY_DOCKER_LOCAL_TAG}" ]] ; then
+        echo "Error: DEPLOY_DOCKER_LOCAL_TAG is required"
+        return 1
+    fi
+
+    if [[ ! -z "${DEPLOY_GITHUB_MACHINE_USER_KEY_FINGERPRINT}" ]] ; then
+
+        fingerprint="$( echo ${DEPLOY_GITHUB_MACHINE_USER_KEY_FINGERPRINT} | tr -d : )"
+
+        eval keyfile="~/.ssh/id_${fingerprint}"
+
+        if [[ ! -f ${keyfile} ]] ; then
+            echo "Error: Unable to find machine user key file"
+            echo "- fingerprint: ${fingerprint}"
+            echo "- keyfile: ${keyfile}"
+
+            eval keyfile="~/.ssh/id_circleci_github"
+
+            if [[ ! -f ${keyfile} ]] ; then
+                echo "Error: Unable to find circle github key file"
+                echo "- keyfile: ${keyfile}"
+                return 1
+            fi
+
+        fi
+
+        echo "Using GITHUB_MACHINE_USER_KEY=${keyfile}"
+
+    fi
+
+    docker build \
+        --rm=false \
+        ${NPM_TOKEN:+ --build-arg NPM_TOKEN=$NPM_TOKEN}\
+        ${keyfile:+ --build-arg GITHUB_MACHINE_USER_KEY="$(< ${keyfile} )"} \
+        -t ${DEPLOY_DOCKER_LOCAL_TAG} \
+        -f ${DEPLOY_DOCKERFILE} \
+        .
+
+}
+
+
+##
+## ecr
+##
+
 function ecr_login () {
 
     echo
@@ -135,7 +197,7 @@ function ecr_login () {
     check_environment
 
     login_command=$(
-        aws --profile=${DEPLOY_AWS_PROFILE} ecr get-login
+        aws --profile=${DEPLOY_AWS_PROFILE} ecr get-login --no-include-email (
     )
 
     if [[ ! "$login_command" =~ "https://${DEPLOY_AWS_ACCOUNT}" ]]; then
@@ -225,6 +287,10 @@ function ecr_push_image () {
     fi
 
 }
+
+##
+## ecs
+##
 
 function ecs_deploy_task () {
 
@@ -370,64 +436,6 @@ function ecs_verify_deploy () {
     exit 1
 }
 
-
-##
-## public functions
-##
-
-function docker_build {
-
-    echo
-    echo Building docker image
-    echo DEPLOY_DOCKERFILE: ${DEPLOY_DOCKERFILE}
-    echo DEPLOY_DOCKER_LOCAL_TAG: ${DEPLOY_DOCKER_LOCAL_TAG}
-    echo
-
-    if [[ -z "${DEPLOY_DOCKERFILE}" ]] ; then
-        echo "Error: DEPLOY_DOCKERFILE is required"
-        return 1
-    fi
-
-    if [[ -z "${DEPLOY_DOCKER_LOCAL_TAG}" ]] ; then
-        echo "Error: DEPLOY_DOCKER_LOCAL_TAG is required"
-        return 1
-    fi
-
-    if [[ ! -z "${DEPLOY_GITHUB_MACHINE_USER_KEY_FINGERPRINT}" ]] ; then
-
-        fingerprint="$( echo ${DEPLOY_GITHUB_MACHINE_USER_KEY_FINGERPRINT} | tr -d : )"
-
-        eval keyfile="~/.ssh/id_${fingerprint}"
-
-        if [[ ! -f ${keyfile} ]] ; then
-            echo "Error: Unable to find machine user key file"
-            echo "- fingerprint: ${fingerprint}"
-            echo "- keyfile: ${keyfile}"
-
-            eval keyfile="~/.ssh/id_circleci_github"
-
-            if [[ ! -f ${keyfile} ]] ; then
-                echo "Error: Unable to find circle github key file"
-                echo "- keyfile: ${keyfile}"
-                return 1
-            fi
-
-        fi
-
-        echo "Using GITHUB_MACHINE_USER_KEY=${keyfile}"
-
-    fi
-
-    docker build \
-        --rm=false \
-        ${NPM_TOKEN:+ --build-arg NPM_TOKEN=$NPM_TOKEN}\
-        ${keyfile:+ --build-arg GITHUB_MACHINE_USER_KEY="$(< ${keyfile} )"} \
-        -t ${DEPLOY_DOCKER_LOCAL_TAG} \
-        -f ${DEPLOY_DOCKERFILE} \
-        .
-
-}
-
 function ecs_deploy () {
 
   # check environment variables
@@ -437,8 +445,8 @@ function ecs_deploy () {
   aws_configure
   ecr_login
 
-  _deploy_image
-  _update_service
+  _ecs_deploy_image
+  _ecs_update_service
 }
 
 function ecs_deploy_image () {
@@ -450,7 +458,7 @@ function ecs_deploy_image () {
     aws_configure
     ecr_login
 
-    _deploy_image
+    _ecs_deploy_image
 }
 
 function ecs_update_service () {
@@ -462,12 +470,130 @@ function ecs_update_service () {
     aws_configure
     ecr_login
 
-    _update_service
+    _ecs_update_service
 }
 
+
 #
-# lamdba
+# TODO: rethink this function and the use of FLM_ENV
 #
+function _get_target_image_tag() {
+  local local_target_tag="${DEPLOY_CURRENT_TIME}-${DEPLOY_SHA1}"
+
+  if [ ! -z "$DEPLOY_ADD_ENV_TO_TAG" ]; then
+    local_target_tag="${local_target_tag}-${FLM_ENV}"
+  fi
+
+  echo $local_target_tag
+}
+
+function _ecs_deploy_image () {
+
+    #
+    # push images
+    #
+
+    if [[ ! -z "${DEPLOY_RETAG_AND_PUSH}" ]] ; then
+
+        remote_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_RETAG_REMOTE_TAG}"
+        target_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_RETAG_TARGET_TAG}"
+
+        echo
+        echo DEPLOY_RETAG_AND_PUSH: ${DEPLOY_RETAG_AND_PUSH}
+        echo remote_tag: ${remote_tag}
+        echo target_tag: ${target_tag}
+        echo
+
+        ecr_pull_image \
+            $remote_tag
+
+        ecr_tag_image \
+            $remote_tag \
+            $target_tag
+
+        ecr_push_image \
+            $target_tag
+
+        DEPLOY_IMAGE="${target_tag}"
+
+    else
+
+        target_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:$(_get_target_image_tag)"
+
+        echo
+        echo Pushing primary tag
+        echo target_tag: ${target_tag}
+        echo
+
+        ecr_tag_image \
+            $DEPLOY_DOCKER_LOCAL_TAG \
+            $target_tag
+
+        ecr_push_image \
+            $target_tag
+
+        if [[ ! -z "$DEPLOY_PUSH_SECONDARY_TAG" ]] ; then
+
+            secondary_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_PUSH_SECONDARY_TAG}"
+
+            echo
+            echo Pushing secondary tag
+            echo secondary_tag: ${secondary_tag}
+            echo
+
+            ecr_tag_image \
+                $target_tag \
+                $secondary_tag
+
+            ecr_push_image \
+                $secondary_tag
+        fi
+
+        DEPLOY_IMAGE="${target_tag}"
+
+    fi
+
+    if [[ -z "${DEPLOY_IMAGE}" ]] ; then
+        echo "Error: deploy image is undefined, DEPLOY_IMAGE=${DEPLOY_IMAGE}"
+        exit 1
+    fi
+
+}
+
+function _ecs_update_service() {
+
+    DEPLOY_IMAGE_TAG="$(_get_target_image_tag)"
+
+    #
+    # deploy task defs
+    #
+
+    # deploy all the tasks first...
+    if [[ -z "$DEPLOY_ECS_FAMILIES" ]] ; then
+
+        ecs_deploy_task $DEPLOY_IMAGE_TAG
+        ecs_verify_deploy
+
+    else
+
+        for family in $DEPLOY_ECS_FAMILIES
+        do
+            ecs_deploy_task $DEPLOY_IMAGE_TAG $family
+        done
+
+        for family in $DEPLOY_ECS_FAMILIES
+        do
+            ecs_verify_deploy $family
+        done
+
+    fi
+
+}
+
+
+##
+## lamdba
+##
 
 function lambda_package_zip () {
 
@@ -788,125 +914,6 @@ function deploy_lambda_event () {
     lambda_deploy_event
 }
 
-##
-##
-##
-
-#
-# TODO: rethink this function and the use of FLM_ENV
-#
-function _get_target_image_tag() {
-  local local_target_tag="${DEPLOY_CURRENT_TIME}-${DEPLOY_SHA1}"
-
-  if [ ! -z "$DEPLOY_ADD_ENV_TO_TAG" ]; then
-    local_target_tag="${local_target_tag}-${FLM_ENV}"
-  fi
-
-  echo $local_target_tag
-}
-
-function _deploy_image () {
-
-    #
-    # push images
-    #
-
-    if [[ ! -z "${DEPLOY_RETAG_AND_PUSH}" ]] ; then
-
-        remote_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_RETAG_REMOTE_TAG}"
-        target_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_RETAG_TARGET_TAG}"
-
-        echo
-        echo DEPLOY_RETAG_AND_PUSH: ${DEPLOY_RETAG_AND_PUSH}
-        echo remote_tag: ${remote_tag}
-        echo target_tag: ${target_tag}
-        echo
-
-        ecr_pull_image \
-            $remote_tag
-
-        ecr_tag_image \
-            $remote_tag \
-            $target_tag
-
-        ecr_push_image \
-            $target_tag
-
-        DEPLOY_IMAGE="${target_tag}"
-
-    else
-
-        target_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:$(_get_target_image_tag)"
-
-        echo
-        echo Pushing primary tag
-        echo target_tag: ${target_tag}
-        echo
-
-        ecr_tag_image \
-            $DEPLOY_DOCKER_LOCAL_TAG \
-            $target_tag
-
-        ecr_push_image \
-            $target_tag
-
-        if [[ ! -z "$DEPLOY_PUSH_SECONDARY_TAG" ]] ; then
-
-            secondary_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_PUSH_SECONDARY_TAG}"
-
-            echo
-            echo Pushing secondary tag
-            echo secondary_tag: ${secondary_tag}
-            echo
-
-            ecr_tag_image \
-                $target_tag \
-                $secondary_tag
-
-            ecr_push_image \
-                $secondary_tag
-        fi
-
-        DEPLOY_IMAGE="${target_tag}"
-
-    fi
-
-    if [[ -z "${DEPLOY_IMAGE}" ]] ; then
-        echo "Error: deploy image is undefined, DEPLOY_IMAGE=${DEPLOY_IMAGE}"
-        exit 1
-    fi
-
-}
-
-function _update_service() {
-
-    DEPLOY_IMAGE_TAG="$(_get_target_image_tag)"
-
-    #
-    # deploy task defs
-    #
-
-    # deploy all the tasks first...
-    if [[ -z "$DEPLOY_ECS_FAMILIES" ]] ; then
-
-        ecs_deploy_task $DEPLOY_IMAGE_TAG
-        ecs_verify_deploy
-
-    else
-
-        for family in $DEPLOY_ECS_FAMILIES
-        do
-            ecs_deploy_task $DEPLOY_IMAGE_TAG $family
-        done
-
-        for family in $DEPLOY_ECS_FAMILIES
-        do
-            ecs_verify_deploy $family
-        done
-
-    fi
-
-}
 
 ##
 ## MAIN
